name: "Convert issue number to project item ID"
author: "Christian Toney"
description: "Convert a project number to an ID. You can use a personal access token (PAT) or GitHub app."
inputs:

  # Project metadata
  github-issue-number:
    description: "The number of the issue that you want to find the item ID of. Required if issue node ID is not provided."
    required: false
  github-issue-id:
    description: "The ID of the issue that you want to find the item ID of. Required if issue number is not provided."
    required: false
  github-project-id:
    description: "The ID of the project that links to the issue."
    required: true
  should-fail-if-issue-not-found:
    description: "If true, the workflow will throw an error if the issue isn't found; otherwise, the output will be undefined."
    required: false

  # Authentication inputs for GitHub app
  github-app-id:
    description: "The ID of your GitHub app. Required if a personal access token is not provided."
    required: false
  github-app-private-key:
    description: "A private key of your GitHub app. Required if a personal access token is not provided."
    required: false
  github-app-installation-id:
    description: "The installation ID of the GitHub app. You can get this from checking the URL after hitting configure at https://github.com/{USER or ORGANIZATION}/{REPOSITORY}/settings/installations."
    required: false
  
  # Authentication inputs for personal access token
  github-personal-access-token:
    description: "The access token of the GitHub account. Required if GitHub app authentication inputs are not provided."
    required: false

runs:
  using: "node20"
  main: "dist/index.js"